# Generated by Django 3.2.3 on 2021-07-26 16:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_test5'),
    ]

    operations = [
        migrations.AddField(
            model_name='test1',
            name='date',
            field=models.DateField(default=datetime.date(2021, 8, 20)),
        ),
    ]
