# Generated by Django 3.2.3 on 2021-07-26 16:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_test1_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='test2',
            name='date',
            field=models.DateField(default=datetime.date(2021, 8, 20)),
        ),
        migrations.AddField(
            model_name='test3',
            name='date',
            field=models.DateField(default=datetime.date(2021, 8, 20)),
        ),
        migrations.AddField(
            model_name='test4',
            name='date',
            field=models.DateField(default=datetime.date(2021, 8, 20)),
        ),
        migrations.AddField(
            model_name='test5',
            name='date',
            field=models.DateField(default=datetime.date(2021, 8, 20)),
        ),
    ]
