# Generated by Django 3.2.3 on 2021-10-04 11:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_test1_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='test1',
            name='time',
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
        migrations.AddField(
            model_name='test2',
            name='time',
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
        migrations.AddField(
            model_name='test3',
            name='time',
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
        migrations.AddField(
            model_name='test4',
            name='time',
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
        migrations.AddField(
            model_name='test5',
            name='time',
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
        migrations.AlterField(
            model_name='test2',
            name='date',
            field=models.DateField(default=datetime.date(2021, 7, 20)),
        ),
        migrations.AlterField(
            model_name='test3',
            name='date',
            field=models.DateField(default=datetime.date(2021, 7, 20)),
        ),
        migrations.AlterField(
            model_name='test4',
            name='date',
            field=models.DateField(default=datetime.date(2021, 7, 20)),
        ),
        migrations.AlterField(
            model_name='test5',
            name='date',
            field=models.DateField(default=datetime.date(2021, 7, 20)),
        ),
    ]
