# Generated by Django 4.2.1 on 2023-06-16 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_test13'),
    ]

    operations = [
        migrations.AddField(
            model_name='test1',
            name='via_telegram',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test10',
            name='via_telegram',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test11',
            name='via_telegram',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test12',
            name='via_telegram',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test13',
            name='via_telegram',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test2',
            name='via_telegram',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test3',
            name='via_telegram',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test4',
            name='via_telegram',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test5',
            name='via_telegram',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test6',
            name='via_telegram',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test7',
            name='via_telegram',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test8',
            name='via_telegram',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test9',
            name='via_telegram',
            field=models.BooleanField(default=False),
        ),
    ]
