# Generated by Django 4.2.1 on 2023-06-18 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_test1_via_telegram_test10_via_telegram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test1',
            name='message',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='test10',
            name='message',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='test11',
            name='message',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='test12',
            name='message',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='test13',
            name='message',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='test2',
            name='message',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='test3',
            name='message',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='test4',
            name='message',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='test5',
            name='message',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='test6',
            name='message',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='test7',
            name='message',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='test8',
            name='message',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='test9',
            name='message',
            field=models.TextField(default=''),
        ),
    ]
