# Generated by Django 3.2.3 on 2021-07-26 16:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210726_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test1',
            name='date',
            field=models.DateField(default=datetime.date(2021, 7, 20)),
        ),
        migrations.AlterField(
            model_name='test2',
            name='date',
            field=models.DateField(default=datetime.date(2021, 7, 20)),
        ),
        migrations.AlterField(
            model_name='test3',
            name='date',
            field=models.DateField(default=datetime.date(2021, 7, 20)),
        ),
        migrations.AlterField(
            model_name='test4',
            name='date',
            field=models.DateField(default=datetime.date(2021, 7, 20)),
        ),
        migrations.AlterField(
            model_name='test5',
            name='date',
            field=models.DateField(default=datetime.date(2021, 7, 20)),
        ),
    ]
